# Generated by Django 4.2.7 on 2026-04-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('query_text', models.TextField(verbose_name='Запрос пользователя')),
                ('bot_response', models.TextField(blank=True, verbose_name='Ответ бота')),
                ('admin_reply', models.TextField(blank=True, verbose_name='Ответ поддержки')),
                ('status', models.CharField(choices=[('answered', 'Отвечено'), ('pending', 'Ожидает ответа'), ('support', 'Передано в поддержку')], default='answered', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата запроса')),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
                'ordering': ['-created_at'],
            },
        ),
    ]
