# Generated by Django 4.2.7 on 2026-05-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('message', models.TextField(verbose_name='Текст уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent', models.BooleanField(default=False, verbose_name='Отправлено')),
                ('sent_count', models.IntegerField(default=0, verbose_name='Отправлено пользователям')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='userquery',
            options={'ordering': ['-created_at'], 'verbose_name': 'Запрос', 'verbose_name_plural': 'Запросы пользователей'},
        ),
        migrations.AlterField(
            model_name='userquery',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='query_text',
            field=models.TextField(verbose_name='Запрос'),
        ),
    ]
