# Generated by Django 4.2.7 on 2026-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_notification_alter_userquery_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Username')),
                ('message', models.TextField(verbose_name='Текст напоминания')),
                ('send_at', models.DateTimeField(verbose_name='Время отправки')),
                ('repeat', models.CharField(choices=[('once', 'Один раз'), ('daily', 'Каждый день'), ('weekly', 'Каждую неделю')], default='once', max_length=10, verbose_name='Повтор')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Напоминание',
                'verbose_name_plural': 'Напоминания',
                'ordering': ['send_at'],
            },
        ),
        migrations.AddField(
            model_name='userquery',
            name='reply_sent',
            field=models.BooleanField(default=False, verbose_name='Ответ отправлен в Telegram'),
        ),
    ]
